services:
    stg.monolog.gelf_handler:
        class: STG\Bundle\MonologGELFBundle\Handler\MonologGELFHandler
        arguments: ['%env(GELF_HOST)%', '%env(GELF_PORT)%', '@request_stack', '%env(GELF_TAG)%', '%env(APP_ENV)%', '%env(GELF_LEVEL)%']

